const { contextBridge, ipcRenderer, clipboard } = require('electron');

contextBridge.exposeInMainWorld('acorde', {
  clipboardRead: () => clipboard.readText(),
  clipboardWrite: (text) => clipboard.writeText(text),
  newScore: (template = 'piano') => ipcRenderer.invoke('file:new', { template }),
  openScore: () => ipcRenderer.invoke('file:open'),
  openRecentScore: (index) => ipcRenderer.invoke('file:openPath', { filePath: index }),
  recentFiles: () => ipcRenderer.invoke('file:recent'),
  saveScore: (payload) => ipcRenderer.invoke('file:save', payload),
  savePdf: (payload) => ipcRenderer.invoke('file:savePdf', payload),
  serializeMusicxml: (score) => ipcRenderer.invoke('engine:serializeMusicxml', { score }),
  renderSvg: (score, width, options = {}) => ipcRenderer.invoke('engine:renderSvg', { score, width, ...options }),
  renderSvgMetadata: (score, width, options = {}) => ipcRenderer.invoke('engine:renderSvgMetadata', { score, width, ...options }),
  applyCommand: (command, label) => ipcRenderer.invoke('engine:applyCommand', { command, label }),
  undo: () => ipcRenderer.invoke('engine:undo'),
  redo: () => ipcRenderer.invoke('engine:redo'),
  renderCurrent: (width) => ipcRenderer.invoke('engine:renderCurrent', { width }),
  loadScore: (score) => ipcRenderer.invoke('engine:loadScore', { score }),
  extractPart: (score, partIndex) => ipcRenderer.invoke('engine:extractPart', { score, partIndex }),
  serializeCurrent: () => ipcRenderer.invoke('engine:serializeCurrent'),
  serializeMidi: (score) => ipcRenderer.invoke('engine:serializeMidi', { score }),
  serializeMusicxmlReport: (score) => ipcRenderer.invoke('engine:serializeMusicxmlReport', { score }),
  serializeAbcReport: (score) => ipcRenderer.invoke('engine:serializeAbcReport', { score }),
  serializeMidiReport: (score) => ipcRenderer.invoke('engine:serializeMidiReport', { score }),
  saveMidi: (payload) => ipcRenderer.invoke('file:saveMidi', payload),
  chooseSoundfont: () => ipcRenderer.invoke('file:chooseSoundfont'),
  chooseOmrInput: () => ipcRenderer.invoke('file:chooseOmrInput'),
  validateSoundfont: (filePath) => ipcRenderer.invoke('file:validateSoundfont', { filePath }),
  readSoundfont: (filePath) => ipcRenderer.invoke('file:readSoundfont', { filePath }),
  playbackEvents: (score, options) => ipcRenderer.invoke('engine:playbackEvents', { score, ...options }),
  playbackPosition: (elapsedSecs, bpm) => ipcRenderer.invoke('engine:playbackPosition', { elapsedSecs, bpm }),
  inspectSoundfont: (data, providerVersion, bank = null, program = null) => ipcRenderer.invoke('engine:inspectSoundfont', { data, provider_version: providerVersion, bank, program }),
  decodeSoundfontSample: (payload) => ipcRenderer.invoke('engine:decodeSoundfontSample', payload),
  normalizeDecodedSample: (sample) => ipcRenderer.invoke('soundfont:normalizeDecodedSample', sample),
  assessOmrProposal: (proposal) => ipcRenderer.invoke('omr:assessProposal', proposal),
  normalizeOmrRunResult: (result) => ipcRenderer.invoke('omr:normalizeRunResult', result),
  findOmrItemAtPoint: (proposal, x, y) => ipcRenderer.invoke('omr:findItemAtPoint', { proposal, x, y }),
  buildAiRequest: (payload) => ipcRenderer.invoke('ai:buildRequest', payload),
  normalizeAiResponse: (response, expectedContextFingerprint = null) => ipcRenderer.invoke('ai:normalizeResponse', { response, expectedContextFingerprint }),
});
